apiVersion: apps/v1
kind: Deployment
metadata:
  name: new-app-a
  namespace: app-a
  annotations:
    build-number: '7'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: new-app-a
  template:
    metadata:
      labels:
        app: new-app-a
    spec:
      containers:
      - name: new-app-a
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: new-app-a
  namespace: app-a
spec:
  selector:
    app: new-app-a
  ports:
  - port: 80
    targetPort: 80
